services:
    apache:
        image: php:8.5-apache
        container_name: signup_php_oo_ap
        build:
            context: ./php
        ports:
            -   "80:80"
        volumes:
            -   ./app:/var/www/html/
        depends_on:
            -   database

    database:
        image: mysql:8.0
        container_name: signup_php_oo_my
        environment:
            MYSQL_ROOT_PASSWORD: admin77911
            MYSQL_DATABASE: signup_php_oo
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin7791
        ports:
            -   "3306:3306"
        volumes:
            -   ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        container_name: signup_php_oo_pma
        ports:
            -   "81:80"
        environment:
            PMA_HOST: database
            PMA_PASSWORD: admin77911
        depends_on:
            -   database

    mail_hog:
        image: mailhog/mailhog
        container_name: signup_php_oo_mail
        logging:
            driver: 'none'
        ports:
            -   "1025:1025"
            -   "8025:8025"
        

    